//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergija> Alergijas { get; set; }
        public virtual DbSet<Brend> Brends { get; set; }
        public virtual DbSet<DetaljiAlergija> DetaljiAlergijas { get; set; }
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Porudzbina> Porudzbinas { get; set; }
        public virtual DbSet<Prodavnica> Prodavnicas { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
        public virtual DbSet<RecenzijaProizvoda> RecenzijaProizvodas { get; set; }
        public virtual DbSet<SlikaProdavnice> SlikaProdavnices { get; set; }
        public virtual DbSet<SlikaProizvoda> SlikaProizvodas { get; set; }
        public virtual DbSet<SlikeBrenda> SlikeBrendas { get; set; }
        public virtual DbSet<StavkaPorudzbine> StavkaPorudzbines { get; set; }
        public virtual DbSet<VrstaProizvoda> VrstaProizvodas { get; set; }
    }
}
