//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int KorisnikID { get; set; }
        public string TipKorisnika { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Kontakt { get; set; }
        public string Adresa { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> BrojStana { get; set; }
        public Nullable<int> UkupnoStanjeBodova { get; set; }
    }
}
