//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porudzbina
    {
        public int PorudzbinaID { get; set; }
        public int CenaPorudzbine { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Isplata { get; set; }
        public bool Zahtev { get; set; }
        public string Komentar { get; set; }
        public string NacinPlacanja { get; set; }
        public int KorisnikID { get; set; }
    }
}
