//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodavnica
    {
        public int ProdavnicaID { get; set; }
        public string NazivProdavnice { get; set; }
        public string Kontakt { get; set; }
        public string Opis { get; set; }
        public string Adresa { get; set; }
        public string RadnoVreme { get; set; }
        public Nullable<int> GradID { get; set; }
    }
}
