//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        public int ProizvodID { get; set; }
        public string NazivProizvoda { get; set; }
        public int Cena { get; set; }
        public string Opis { get; set; }
        public int OcenaProizvoda { get; set; }
        public Nullable<int> VrstaProidvodaID { get; set; }
        public Nullable<int> BrendID { get; set; }
        public Nullable<int> ProdavnicaID { get; set; }
    }
}
