//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecenzijaProizvoda
    {
        public int RecenzijaProizvodaID { get; set; }
        public int Ocena { get; set; }
        public string Komentar { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<bool> Odobrena { get; set; }
        public Nullable<int> ProizvodID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
    }
}
