//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaPorudzbine
    {
        public int StavkaPorudzbineID { get; set; }
        public int KolicinaProizvoda { get; set; }
        public Nullable<int> ProizvodID { get; set; }
        public Nullable<int> PorudzbinaID { get; set; }
    }
}
